### ISSUE TITLE
Figure out and implement a story for Open/Closed channels

### ISSUE THREAD

**Issue by mniip** [discord-math/bot#7]
Ideas include:
- Renaming channels to open/closed as well as moving them between open/closed categories.
- Assigning the channel to the first person who speaks. Tracking activity in the channel and after a certain timeout asking that user whether their question has been answered. If yes, return channel to open pool. If not, raise the timeout and watch activity again.
- Commands for manual management of openness.
- Disallow the asker to claim another open channel.

**Comment by Element118** [comment]
though how do we prevent interrupts, and how do we tell the difference between an interrupting person and someone helping?
should people have to register some role before they can answer questions?

**Comment by mniip** [comment]
I would expect that if the channel is marked "occupied", it would discourage people well enough from posting their question in it. In case people still do (which I expect to be super rare), I don't expect an automated reaction from the bot will be needed, and people can step in and intervene/rectify the situation.

I am extremely opposed against a role requirement for answering questions by the way.

**Comment by mniip** [comment]
Implemented.
