### ISSUE TITLE
Add CI/CD for PR build tests

### ISSUE THREAD

**Issue by Brandon-Huu** [discord-math/bot#70]
bottom text

**Comment by Brandon-Huu** [comment]
> This is working as intended. Workflows are run when approved by a maintainer.

why?

**Comment by rattus-rattus-rattus** [comment]
This is built-in [GitHub Actions behavior](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/).

**Comment by Brandon-Huu** [comment]
> This is built-in [GitHub Actions behavior](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/).

I'm no realizing my request was kinda insane.
This is python, there is no building
